# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Homarr installation tasks
  when: homarr_enabled | bool
  tags:
    - setup-all
    - setup-homarr
    - install-all
    - install-homarr
  block:
    - name: Validate Homarr configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Homarr
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Homarr uninstallation tasks
  when: not homarr_enabled | bool
  tags:
    - setup-all
    - setup-homarr
  block:
    - name: Uninstall Homarr
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
