# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- block:
    - when: homarr_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: homarr_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

  tags:
    - setup-all
    - setup-homarr
    - install-all
    - install-homarr

- block:
    - when: not homarr_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-homarr
