# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Homarr systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ homarr_identifier }}.service"
  register: homarr_service_stat

- name: Uninstall Homarr systemd services and files
  when: homarr_service_stat.stat.exists | bool
  block:
    - name: Ensure Homarr systemd service is stopped
      ansible.builtin.service:
        name: "{{ homarr_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Homarr systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ homarr_identifier }}.service"
        state: absent

    - name: Ensure Homarr support files do not exist
      ansible.builtin.file:
        path: "{{ homarr_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure Homarr container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ homarr_container_network }}"
        state: absent

    - name: Ensure Homarr container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ homarr_container_network }}
      register: network_deletion_result
      changed_when: homarr_container_network in network_deletion_result.stdout

- name: Check existence of Homarr local data path
  ansible.builtin.stat:
    path: "{{ homarr_data_path }}"
  register: homarr_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if Homarr local data remains
  when: homarr_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As a local Homarr instance has been removed, some old data remains in `{{ homarr_data_path }}`. Feel free to delete it."
        ]
      }}
