# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "homarr_environment_variables_db_driver", "new": "homarr_database_type" }
    - { "old": "homarr_environment_variables_db_url", "new": "homarr_database_url" }
    - { "old": "homarr_environment_variables_db_host", "new": "homarr_database_mysql_hostname" }
    - { "old": "homarr_environment_variables_db_hostname", "new": "homarr_database_mysql_hostname" }
    - { "old": "homarr_environment_variables_db_port", "new": "homarr_database_mysql_port" }
    - { "old": "homarr_environment_variables_db_user", "new": "homarr_database_mysql_username" }
    - { "old": "homarr_environment_variables_db_password", "new": "homarr_database_mysql_password" }
    - { "old": "homarr_environment_variables_db_name", "new": "homarr_database_name" }
    - { "old": "homarr_http_header_content_permission_policy", "new": "homarr_http_header_permissions_policy" }

- name: Fail if required Homarr settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - homarr_uid
    - homarr_gid
    - homarr_hostname
    - homarr_path_prefix
    - homarr_container_network
    - homarr_data_path
    - homarr_environment_variables_secret_encryption_key

- name: Fail if Homarr database type is invalid
  ansible.builtin.fail:
    msg: >-
      homarr_database_type must be 'better-sqlite3', 'mysql2', or 'node-postgres'
  when: "homarr_database_type not in ['better-sqlite3', 'mysql2', 'node-postgres']"

- name: Fail if required Homarr + MySQL2 integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `homarr_database_type` is `mysql2`
  when: "homarr_database_type == 'mysql2' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - homarr_database_mysql_hostname
    - homarr_database_mysql_password

- name: Fail if required Homarr + node-postgres integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `homarr_database_type` is `node-postgres`
  when: "homarr_database_type == 'node-postgres' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - homarr_database_postgres_hostname
    - homarr_database_postgres_password

- name: Fail if Homarr Docker endpoint syntax invalid
  ansible.builtin.fail:
    msg: >-
      homarr_docker_endpoint must look like `unix:///var/run/docker.sock` or `tcp://host:2345`
  when: "not (homarr_docker_endpoint.startswith('unix://') or homarr_docker_endpoint.startswith('tcp://'))"

- name: Run if Traefik is enabled
  when: homarr_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Homarr are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - homarr_container_labels_traefik_hostname
        - homarr_container_labels_traefik_path_prefix

    - name: Fail if homarr_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          homarr_container_labels_traefik_path_prefix (`{{ homarr_container_labels_traefik_path_prefix }}`) must be `/`.
          Homarr does not support hosting under a subpath yet.
      when: "homarr_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `homarr_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if homarr_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          homarr_container_labels_traefik_path_prefix (`{{ homarr_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/homarr`).
      when: "homarr_container_labels_traefik_path_prefix != '/' and homarr_container_labels_traefik_path_prefix[-1] == '/'"
